name:                mappings
version:             0.3.0.0
github:              "jcranch/mapping"
license:             BSD-3-Clause
author:              "James Cranch"
maintainer:          "j.d.cranch@sheffield.ac.uk"
copyright:           "2023 James Cranch"

extra-doc-files:
- README.md
- CHANGELOG.md

synopsis:            Types which represent functions k -> v
category:            Data structures

description:         A typeclass and a number of implementations; please read README.md on github

dependencies:
- base                   >= 4.16      &&  < 4.20
- cond                   >= 0.5.1     &&  < 0.6
- containers             >= 0.6.5     &&  < 0.8
- formatting             >= 7.0.0     &&  < 7.3
- indexed-traversable    >= 0.1.1     &&  < 0.2
- partialord             >= 0.0.2     &&  < 0.1

language:            GHC2021

# Tested-With:         GHC ==9.2.8 || ==9.4.7 || ==9.6.3

library:
  source-dirs: src
  ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints

executables:
  view:
    main:                View.hs
    source-dirs:         examples
    ghc-options:
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mappings

tests:
  mapping:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hspec                          >= 2.11     && < 2.12
    - mappings
    build-tool-depends:
    - hspec-discover:hspec-discover  >= 2.11     && < 2.12
