name:                mappings
version:             0.0.1.0
github:              "jcranch/mapping"
license:             BSD-3-Clause
author:              "James Cranch"
maintainer:          "j.d.cranch@sheffield.ac.uk"
copyright:           "2023 James Cranch"

extra-source-files:
- README.md
- CHANGELOG.md

synopsis:            Types which represent functions k -> v
category:            Data structures

description:         Please read README.md on github

dependencies:
- base                   >= 4.18      &&  < 4.20
- cond                   >= 0.4       &&  < 0.5
- containers             >= 0.6.6     &&  < 0.7
- formatting             >= 7.0.0     &&  < 7.3
- partialord             >= 0.0.2     &&  < 0.1

language:            GHC2021

library:
  source-dirs: src
  ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints

executables:
  view:
    main:                View.hs
    source-dirs:         examples
    ghc-options:
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mappings

tests:
  mapping:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mappings
    - hspec        >= 2.11     && < 2.12
